### ISSUE TITLE
Spelling Mistake/HTML tag issues in Content

### ISSUE THREAD

**Issue by iamanandhu** [MicrosoftDocs/Advertising#6]
[Enter feedback here]

**The Currency details guide has a spelling/HTML tag issue mismatch. Please have a look at the image attached.**

![Products-Resource-Microsoft-Advertising-Microsoft-Docs](https://user-images.githubusercontent.com/20636587/137121965-bfe030ca-5832-4cd4-ae24-03a07c7756e9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 133b8cc8-7ab7-a2c6-b0fc-14a5fb60159f
* Version Independent ID: 3d0c3d20-66c5-1b26-fed1-0a3315bbc954
* Content: [Products Resource - Microsoft Advertising](https://docs.microsoft.com/en-us/advertising/shopping-content/products-resource#feedback)
* Content Source: [advertising/shopping-content/products-resource.md](https://github.com/MicrosoftDocs/Advertising/blob/main/advertising/shopping-content/products-resource.md)
* Service: **bing-ads-shopping-content**
* GitHub Login: @eric-urban
* Microsoft Alias: **eur**

**Comment by eric-urban** [comment]
@iamanandhu - Thanks for letting us know! This is [fixed](https://github.com/MicrosoftDocs/Advertising/commit/46e89e02717d0c62ff47a7afd95b1f2d88ba0c57) and we will publish live soon.
